services:
    # redis-microservice:
    #     image: redis:7-alpine
    #     container_name: redis
    #     restart: on-failure
    #     ports:
    #         - '6379:6379'
    #     volumes:
    #         - my_diplom_redis_data:/data
    #     command: ['redis-server', '--appendonly', 'yes']
    postgres-diplom:
        image: postgres:15
        container_name: postgres-my-diplom-db
        environment:
            POSTGRES_DB: my_diplom
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - '5432:5432'
        volumes:
            - postgres_diplom_data:/var/lib/postgresql/data

volumes:
    my_diplom_redis_data:
    postgres_diplom_data:
